Respect the predefined value of the composition UID when creating new compositions
ehrbase/ehrbase pull request #1089
Opened 2023-03-29 14:02 UTC by stefanspiska

2023-03-29 20:39 UTC, sidharthramesh commented
great feature 👍

This however will still not allow creating a new composition with a UUID using the PUT method right?

2023-03-30 17:13 UTC, HolgerReiseVSys requested changes
Looks good, just few niceties

2023-03-30 17:13 UTC, HolgerReiseVSys commented on service/src/main/java/org/ehrbase/service/CompositionServiceImp.java
> +            if (Integer.parseInt(objectVersionId.getVersionTreeId().getValue()) != 1) {
Could be simpler: First check
`"1".equals(objectVersionId.getVersionTreeId().getValue()`
and then 
`objectVersionId.isBranch()` 
to see what is wrong

2023-03-31 08:05 UTC, HolgerReiseVSys approved these changes

2023-03-31 12:04 UTC, merged