CDR-1616 Refactor allow-template overwrite
ehrbase/ehrbase pull request #1440
Opened 2024-11-28 11:26 UTC by alexlehn

# Changes

Fixed template overwrite and renamed old property from `system.allow-template-overwrite` (`SYSTEM_ALLOWTEMPLATEOVERWRITE`) to `ehrbase.template..allow-overwrite` (`EHRBASE_TEMPLATE_ALLOWOVERWRITE`)

see #1411 

# Pre-Merge checklist

- [x] New code is tested
- [x] Present and new tests pass
- [x] Documentation is updated
- [x] The build is working without errors
- [x] No new Sonar issues introduced
- [x] Changelog is updated
- [ ] Code has been reviewed

2024-11-29 10:30 UTC, stefanspiska requested changes
test should be moved to robot test

2024-12-03 14:48 UTC, stefanspiska commented on service/src/test/java/org/ehrbase/service/TemplateDBStorageServiceTest.java
> +        // mock not exist
mock exist

2024-12-03 14:49 UTC, stefanspiska commented on service/src/test/java/org/ehrbase/service/TemplateDBStorageServiceTest.java
> +        // mock not exist and in use
mock exist and in use

2024-12-03 14:49 UTC, stefanspiska commented on service/src/test/java/org/ehrbase/service/TemplateDBStorageServiceTest.java
> +        // mock not exist and in use
mock exist and in use

2024-12-03 15:01 UTC, alexlehn commented on service/src/test/java/org/ehrbase/service/TemplateDBStorageServiceTest.java
> +        // mock not exist
thx ... fixed

2024-12-03 15:01 UTC, alexlehn commented on service/src/test/java/org/ehrbase/service/TemplateDBStorageServiceTest.java
> +        // mock not exist and in use
thx ... fixed

2024-12-03 15:01 UTC, alexlehn commented on service/src/test/java/org/ehrbase/service/TemplateDBStorageServiceTest.java
> +        // mock not exist and in use
thx ... fixed

2024-12-03 15:04 UTC, stefanspiska approved these changes

2024-12-03 15:25 UTC, merged