Feature/sync/527 update archie dependencies
ehrbase/ehrbase pull request #570
Opened 2021-08-20 11:20 UTC by jakesmolka

## WIP

Missing fixes for test data validation problems:

- [ ] DV_EHR_URI: often uses ~`"value": "target2"` but should be like `"value": "ehr:/target2"` -> throws EHRbase exception

## Changes

- First change

## Related issue

EHRbase side of:
https://github.com/ehrbase/project_management/issues/527

## Additional information and checks

- [ ] Pull request linked in changelog

2021-09-04 03:36 UTC, ppazos requested changes

2021-09-04 03:36 UTC, ppazos commented on tests/robot/_resources/test_data_sets/contributions/invalid/minimal/minimal_admin.contribution.modification.json
> +          "archetype_details": {
@jakesmolka archetype_details should be optional https://specifications.openehr.org/releases/RM/Release-1.1.0/common.html#_overview_2

2021-09-04 03:36 UTC, ppazos commented on tests/robot/_resources/test_data_sets/contributions/invalid/minimal_persistent/minimal_persistent.contribution.modification.json
> +					"archetype_details": {
@jakesmolka archetype_details should be optional https://specifications.openehr.org/releases/RM/Release-1.1.0/common.html#_overview_2

2021-09-04 03:36 UTC, ppazos commented on tests/robot/_resources/test_data_sets/contributions/invalid/ref_to_non_existent_OPT.json
> +					"archetype_details": {
@jakesmolka archetype_details should be optional https://specifications.openehr.org/releases/RM/Release-1.1.0/common.html#_overview_2

2021-09-04 03:36 UTC, ppazos commented on tests/robot/_resources/test_data_sets/invalid_templates/minimal_persistent/persistent_minimal.composition.extdatetime.invalid.xml
> +      <archetype_details>
@jakesmolka archetype_details should be optional https://specifications.openehr.org/releases/RM/Release-1.1.0/common.html#_overview_2

2021-09-06 15:26 UTC, ppazos approved these changes
:shipit:

2021-09-07 07:15 UTC, jakesmolka commented on README.md
> +
I'll add that part to the documentation.

2021-09-10 09:56 UTC, merged